### ISSUE TITLE
mark down component spike

### ISSUE THREAD

**Issue by mandie12** [LastHopeAnimalCharity/planning#9] opened 2018-12-05 15:32 UTC
As a WebSite Administrator
I want to add some content using markdown editor on gh_pages 
This will automatically update content on to the website

**Comment by mkristiansen** [comment] 2019-01-01 15:38
@mandie12 
Starting with this one.. could we please ensure each task documents at high level what is required to mark complete. ie basic acceptance criteria

**Comment by mandie12** [comment] 2019-01-03 21:06
@mkristiansen please correct if you believe this is the wrong description

**Comment by mkristiansen** [comment] 2019-01-04 09:09
Thanks, that looks reasonable.
If you want to stick to agile user stories for technical tasks that's perfectly fine but if you prefer other formats that's ok too.

**Comment by mkristiansen** [comment] 2019-01-09 11:59
Closing as duplicate of #12. Verified with @Gosiaisean that edits to markdown content on gh automatically pushes to the site.

**Closed as completed by mkristiansen** 2019-01-09 11:59 UTC
